export enum Status {
  SUCCESS = 'SUCCESS',
  UNKNOWN_USER = 'UNKNOWN_USER',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  NONE = 'NONE',
  PENDING = 'PENDING',
  PROGRESS = 'PROGRESS',
  FINISHED = 'FINISHED',
  DECLINED = 'DECLINED',
}
