export enum ValidationErrors {
  EMAIL_INVALID = 'EMAIL_INVALID',
  PASSWORD_NOT_MATCHING = 'PASSWORD_NOT_MATCHING',
  PASSWORD_TO_SHORT = 'PASSWORD_TO_SHORT',
  PASSWORD_TO_LONG = 'PASSWORD_TO_LONG',
  TEXTFIELD_EMPTY = 'TEXTFIELD_EMPTY',
  DATE_INVALIDE = 'DATE_INVALIDE',
  PARTNER_ID_NOT_VALID = 'PARTNER_ID_NOT_VALID',
  SCOPE_EMPTY = 'SCOPE_EMPTY',
  VALID = 'VALID',
}
